version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
       - 4000:4000 
  redis-server: 
      image: redis:5.0
      command: redis-server
      
  mongo-server:
      image: mongo:5.0.2
 

   
   
