version: '3.7'


services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment: 
        - PORT=4000
        - REDIS_HOST=redis-server
        - REDIS_PORT=6379
        - MONGO_HOST=mongo-server
        - MONGO_PORT=27017
        - MONGO_DATABASE=app-restaurant
        - MONGO_USER=
        - MONGO_PASSWORD=
        - MONGO_REPLICASET=
        - MONGO_SSL=0
        - MONGO_AUTH_SOURCE=
        - MONGO_CONNECTION_NAME=connection_mongo_1
        - NODE_ENV=development
    ports:
       - 4000:4000 
  redis-server: 
      image: redis:latest
      command: redis-server
      
  mongo-server:
      image: mongo:5.0.2
 

   
   
