
version: '3.7'

services:
  api:
    image: kevinfuentesio/app-restaurant:latest
    ports:
       - 4000:4000 
  redis-server: 
      image: redis:5.0
      command: redis-server
      
  mongo-server:
      image: mongo:5.0.2


  