version: '3.7'


services:
  apprestaurant:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ./.env
    environment:   
      - PORT = $PORT
      - MONGO_HOST = $MONGO_HOST_DOCKER
      - MONGO_PORT = $MONGO_PORT
      - MONGO_DATABASE = $MONGO_DATABASE
      - MONGO_CONNECTION_NAME = $MONGO_CONNECTION_NAME
      - MONGO_USER=  
      - MONGO_PASSWORD=  
      - MONGO_SSL= $MONGO_SSL
      - REDIS_HOST = $REDIS_HOST_DOCKER
      - REDIS_PORT = $REDIS_PORT
    ports:
       - 4000:4000 
  redis-server: 
      image: redis:latest
      command: redis-server
      
  mongo-server:
      image: mongo:5.0.2
 

   
   
