### GET FOOD
GET http://localhost:4000/api/v1/foods?page=2&limit=10

### GET BY ID

GET http://localhost:4000/api/v1/foods/618c12a6adeb13145f97bee2



### POST FOOD
POST http://localhost:4000/api/v1/foods/  
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoia2V2aW4iLCJyb2wiOiJhZG1pbiIsImlhdCI6MTYzNjY1NTc2MX0.D2ldLCmmBS_IKkTP0oFJCBaJ9IVQsOjsopDEAZ2vvys

{
    "name": "Sandwich con jamon y queso",
    "price": "2",
    "type":"fast food"
}


### PATCH FOOD
PATCH   http://localhost:4000/api/v1/foods/618c12a6adeb13145f97bee
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoia2V2aW4iLCJyb2wiOiJhZG1pbiIsImlhdCI6MTYzNjY1NTc2MX0.D2ldLCmmBS_IKkTP0oFJCBaJ9IVQsOjsopDEAZ2vvys

{
  "name":"queso"
}

### DELETE FOOD
DELETE   http://localhost:4000/api/v1/foods/6186b7485999f712e6ce8aab
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoia2V2aW4iLCJyb2wiOiJhZG1pbiIsImlhdCI6MTYzNjY1NTc2MX0.D2ldLCmmBS_IKkTP0oFJCBaJ9IVQsOjsopDEAZ2vvys

