### GET FOOD
GET http://localhost:4000/api/v1/foods?page=1&limit=10

### GET BY ID

GET http://localhost:4000/api/v1/foods/618c12a6adeb13145f97bee8



### POST FOOD
POST http://localhost:4000/api/v1/foods/  
content-type: application/json

{
    "name": "Papas  rellenas",
    "price": "2",
    "type":"fast food"
}


### PATCH FOOD
PATCH   http://localhost:4000/api/v1/foods/618c12a6adeb13145f97bee
content-type: application/json

{
  "name":"queso"
}

### DELETE FOOD
DELETE   http://localhost:4000/api/v1/foods/6186b7485999f712e6ce8aab

