name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: | 
        echo "{{secrets.DOCKER_PASSWORD}}" | docker login -u "kevinfuentesio" --password-stdin
        docker build  -t kevinfuentesoi/app-restaurant:v1 .
        docker push kevinfuentesio/app-restaurant:v1
    
