
name: flow-job-condorlabs
on: [pull_request]
env:
  MONGO_CONNECTION_NAME:  ${{ secrets.MONGO_CONNECTION_NAME }}
  MONGO_HOST: ${{ secrets.MONGO_HOST }}
  MONGO_PORT": ${{ secrets.MONGO_PORT }}
  MONGO_DATABASE: ${{ secrets.MONGO_DATABASE }}
  MONGO_USER: ${{ secrets.MONGO_USER }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
  MONGO_SSL: ${{ secrets.MONGO_SSL }}
  MONGO_REPLICASET: ${{ secrets.MONGO_REPLICASET }}
  MONGO_AUTH_SOURCE: ${{ secrets.MONGO_AUTH_SOURCE }}
  MONGO_DATABASE_TEST: ${{ secrets.MONGO_DATABASE_TEST }}
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm i
      - run: npm run lint-global
      - run: npm test
