
name: flow-job-condorlabs
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      services:
        node-version: [14.18.x]
        mongodb-version: [5.0.x]
        redis-version: [5.x]
    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ services.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ services.node-version }}

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.6.0
      with:
        mongodb-version: ${{ services.mongodb-version }}
        
    - name: Start Redis
      uses: supercharge/redis-github-action@1.2.0
      with:
        redis-version: ${{ services.redis-version }}
        
    - run: npm i
    - run: npm run lint-global
    - run: npm test
      env:  
       CI: true 
