
name: flow-job-condorlabs
on: [pull_request]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    services:
        mongo:
          image: mongo
          env:
            MONGO_INITDB_ROOT_USERNAME: ${APP_MONGO_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${APP_MONGO_PASS}
            MONGO_INITDB_DATABASE: ${APP_MONGO_DB}
          ports:
            - 27017:27017
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm i
      - run: npm run lint-global
      - run: npm test
