
name: flow-job-condorlabs
on: [pull_request]
env:
  MONGO_CONNECTION_NAME:  ${{ secrets.MONGO_CONNECTION_NAME }}
  MONGO_HOST: ${{ secrets.MONGO_HOST }}
  MONGO_PORT": ${{ secrets.MONGO_PORT }}
  MONGO_DATABASE: ${{ secrets.MONGO_DATABASE }}
  MONGO_USER: ${{ secrets.MONGO_USER }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
  MONGO_SSL: ${{ secrets.MONGO_SSL }}
  MONGO_REPLICASET: ${{ secrets.MONGO_REPLICASET }}
  MONGO_AUTH_SOURCE: ${{ secrets.MONGO_AUTH_SOURCE }}
  MONGO_DATABASE_TEST: ${{ secrets.MONGO_DATABASE_TEST }}
  CI: true 
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        mongodb-version: ['5.0']
        redis-version: [5]
    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.6.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
        
    - name: Start Redis
      uses: supercharge/redis-github-action@1.2.0
      with:
        redis-version: ${{ matrix.redis-version }}
        
    - run: npm i
    - run: npm run lint-global
    - run: npm test
