
name: flow-job-condorlabs
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PORT : 4000
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
      REDIS_PASS: ${{ secrets.REDIS_PASS }}
      MONGO_CONNECTION_NAME : ${{ secrets.MONGO_CONNECTION_NAME }}
      MONGO_HOST: ${{ secrets.MONGO_HOST }}
      MONGO_PORT: ${{ secrets.MONGO_PORT }}
      MONGO_DATABASE: ${{ secrets.MONGO_DATABASE }}
      MONGO_USER: ${{ secrets.MONGO_USER }}
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
      MONGO_SSL: ${{ secrets.MONGO_SSL }}
      MONGO_REPLICASET: ${{ secrets.MONGO_REPLICASET }}
      MONGO_AUTH_SOURCE: ${{ secrets.MONGO_AUTH_SOURCE }}
      MONGO_DATABASE_TEST: ${{ secrets.MONGO_DATABASE_TEST }}
    strategy:
      matrix:
        node-version: [14.18.1]
    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - run: npm i
    - run: npm run lint-global
    - run: npm test
 
